---
- name: Configure venv
  hosts: all
  gather_facts: true
  become: no

  tasks:   
    - command: hostname
    
    - command: id
    
    - pip:
        virtualenv: "{{ virtualenv }}"
        umask: "0022"
        state: present
        name:
          - django>1.11.0,<1.12.0
          - bottle>0.10,<0.20,!=0.11
          - ansible==2.8.1
