---
- name: Configure venv
  hosts: all
  gather_facts: true
  become: no

  tasks:
    - debug:
        msg: Hello world
        
    - command: hostname
    
    - command: id
        
    - python_requirements_facts:
        dependencies:
          - openshift
          - requests
                
