---
- name: Configure venv
  hosts: all
  gather_facts: true
  become: no
  
  #vars:
  #  ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - debug:
        msg: Hello world
        
    - command: hostname
    
    - command: id
    
    - command: ansible --version
        
    - python_requirements_facts:
        dependencies:
          - openshift
          - requests
                
